# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='firstname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
