# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20170729_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
