# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_auto_20170729_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('contactNum', models.IntegerField()),
                ('insID', models.IntegerField()),
                ('insNetwork', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='medicalChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason_for_visit', models.TextField(default='', max_length=250)),
                ('height', models.CharField(default='', max_length=10)),
                ('weight', models.IntegerField()),
                ('temperature', models.CharField(default='', max_length=3)),
                ('pulse', models.CharField(max_length=10)),
                ('diagnosis', models.TextField(max_length=250)),
                ('additionalNotes', models.TextField(max_length=250)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profilePic',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/image/'),
        ),
        migrations.AddField(
            model_name='medicalchart',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient'),
        ),
    ]
