# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_auto_20170804_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalchart',
            name='blood_pressure',
            field=models.CharField(default='', max_length=10),
        ),
    ]
