# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0005_medicalchart_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profilePic',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics'),
        ),
    ]
