# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0006_auto_20170805_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient')),
            ],
        ),
    ]
