# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appOne', '0007_additionaldocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('chargeDate', models.DateField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Appointment')),
            ],
        ),
        migrations.RemoveField(
            model_name='additionaldocuments',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='additionaldocuments',
            name='patient',
        ),
        migrations.DeleteModel(
            name='additionalDocuments',
        ),
    ]
