# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('appOne', '0008_auto_20170805_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recieptionist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Recieptionist', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='billinglog',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Doctor'),
        ),
        migrations.AddField(
            model_name='billinglog',
            name='nurse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appOne.Nurse'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Doctor'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient'),
        ),
        migrations.AddField(
            model_name='billinglog',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appOne.Recieptionist'),
        ),
    ]
