# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0009_auto_20170805_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinglog',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='billinglog',
            name='chargeDate',
        ),
        migrations.RemoveField(
            model_name='billinglog',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='billinglog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='billinglog',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
        migrations.AddField(
            model_name='billinglog',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOne.Patient'),
        ),
    ]
